### ISSUE TITLE
[feat] Google Analytics ,Hotjar, Mixpanel 세팅

### ISSUE THREAD

**Issue by ngsy** [GymHubCommunity/GymHub-FE#35]
### 🏋🏻 어떤 개발 사항인가요?

사용자 피드백을 수집하기 위한 툴 세팅 

Google Analytics  :방문자의 유입 소스나 사이트 내 행동과 같은 유용한 정보를 수집하고 저장, 분석을 위한 '웹 로그 분석 분석툴'

Hotjar : '사용자 행동 트레킹 툴' 사이트에 접속해 어떤 행동을 하는지  시각적 자료(영상,히트맵 등)로 수집

Mixpanel : 이벤트 기반 분석을 통해 사용자의 특정 행동과 상호 작용을 추적

### 💪🏻 TODO

- [x] Google Analytics 세팅

- [x] Hotjar 세팅

- [x] Mixpanel 세팅

**Comment by hanseulhee** [comment]
헐 ~~~ 셋팅에서 세팅으로 바꼈당 ㅋ

**Comment by ngsy** [comment]
> 헐 ~~~ 셋팅에서 세팅으로 바꼈당 ㅋ

셋팅이 뭐죠 전 MZ라 잘 모르겠군요 하하
